namespace: monitoring

helmCharts:
- name: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  version: 6.49.0
  valuesFile: loki.values.yml
  namespace: monitoring
  apiVersions:
    - monitoring.coreos.com/v1/PrometheusRule
